import random

hangman_words = [
    "mystery", "adventure", "giraffe", "bicycle", "whisper", "pyramid", "galaxy", "chocolate",
    "elephant", "rainbow", "castle", "treasure", "horizon", "volcano", "oxygen", "universe",
    "phoenix", "tornado", "dragon", "astronaut", "diamond", "keyboard", "butterfly", "crocodile",
    "lighthouse", "icicle", "snowflake", "puzzle", "penguin", "banana", "cactus", "mountain",
    "safari", "jungle", "robot", "vampire", "compass", "lightning", "guitar", "zombie",
    "emerald", "potion", "unicorn", "starlight", "voyage", "mermaid", "pirate", "shark",
    "orchestra", "candle", "trapeze", "meteor", "insect", "labyrinth", "telescope", "spaceship",
    "carnival", "notebook", "piano", "clockwork", "raccoon", "abyss", "eclipse", "cyclone",
    "spectacle", "banquet", "magician", "ballet", "ocean", "forest", "vortex", "submarine",
    "specter", "harmony", "kingdom", "zephyr", "sphinx", "crescent", "fossil", "nebula",
    "alchemy", "bonfire", "falcon", "avalanche", "serpent", "glimmer", "parachute", "chandelier",
    "glacier", "quicksand", "thunderstorm", "rendezvous", "blizzard", "hologram", "oracle",
    "mariner", "quagmire", "galleon", "fireworks", "moonlight", "echo", "harbor", "shipwreck",
    "galactic", "enigma", "cascade", "harbinger", "mirage", "dolphin", "avalon", "kingfisher",
    "stargazer", "euphoria", "wanderlust", "meadow", "frostbite", "cloak", "timepiece", "navigator",
    "aurora", "dragonfly", "shoreline", "equinox", "silhouette", "basilisk", "moonbeam", "prism",
    "vanguard", "voyager", "eldritch", "evergreen", "infinity", "astronomy", "lantern",
    "serenade", "quicksilver", "seafarer", "cryptic", "solstice", "serendipity", "epiphany",
    "ethereal", "turbulence", "aegis", "odyssey", "sapphire", "equilibrium", "excalibur",
    "radiance", "celestial", "avalanche", "paragon", "cosmic", "solitude", "galactic",
    "moonlit", "oasis", "zenith", "quasar", "frost", "tranquil", "nebula", "storm",
    "thunder", "aether", "bliss", "eclipse", "orion", "nova", "constellation", "supernova",
    "polaris", "celestial", "meteorite", "comet", "interstellar", "galaxy", "astronaut",
    "astronomy", "nebula", "cosmos", "voyager", "vortex", "lunar", "solar", "quasar",
    "blackhole", "milkyway", "orbit", "planet", "saturn", "jupiter", "mars", "venus",
    "earth", "moon", "asteroid", "comet", "meteor", "gravity", "space", "lightyear",
    "wormhole", "galaxy", "star", "universe", "sun", "rocket", "satellite", "alien",
    "astronomy", "eclipse", "meteor", "blackhole", "supernova", "andromeda", "solar",
    "lunar", "cosmos", "space", "orbit", "galaxy", "milkyway", "asteroid", "planet",
    "star", "gravity", "comet", "earth", "mars", "jupiter", "neptune", "saturn",
    "venus", "pluto", "uranus", "mercury", "orbit", "rotation", "eclipse", "lunar",
    "supernova", "meteorite", "blackhole", "galactic", "stellar", "nebula", "quasar",
    "asterism", "redshift", "bluegiant", "redgiant", "whitehole", "gamma", "quanta",
    "pulsar", "quasar", "darkmatter", "antimatter", "neutrino", "photon", "wavelength",
    "horizon", "event", "singularity", "ion", "atom", "particle", "energy",
    "frequency", "amplitude", "wavelength", "spectrum", "infrared", "ultraviolet",
    "quantum", "theory", "relativity", "gravity", "nucleus", "electron", "proton",
    "neutron", "quark", "higgs", "boson", "fermion", "hadron", "lepton",
    "meson", "baryon", "quantum", "mechanics", "theory", "physics", "science",
    "research", "experiment", "discovery", "invention", "technology", "engineering",
    "mathematics", "algebra", "geometry", "trigonometry", "calculus", "statistics",
    "probability", "equation", "formula", "algorithm", "function", "derivative",
    "integral", "matrix", "vector", "tensor", "transformation", "symmetry",
    "fractal", "topology", "number", "sequence", "series", "set",
    "group", "ring", "field", "module", "representation", "homomorphism",
    "isomorphism", "automorphism", "endomorphism", "functor", "category",
    "theory", "model", "logic", "proof", "theorem", "lemma",
    "corollary", "axiom", "postulate", "conjecture", "hypothesis", "law",
    "principle", "concept", "idea", "theory", "hypothesis", "experiment",
    "observation", "measurement", "data", "analysis", "interpretation",
    "conclusion", "prediction", "simulation", "model", "equation",
    "system", "interaction", "force", "energy", "power",
    "work", "momentum", "impulse", "acceleration", "velocity",
    "speed", "distance", "displacement", "time", "clock",
    "calendar", "sun", "moon", "star", "planet",
    "satellite", "spacecraft", "rocket", "astronaut", "mission",
    "journey", "exploration", "discovery", "innovation", "technology",
    "research", "development", "design", "engineering", "invention",
    "creativity", "imagination", "idea", "concept", "project",
    "plan", "strategy", "tactic", "method", "technique",
    "procedure", "process", "step", "action", "movement",
    "motion", "gesture", "posture", "pose", "expression",
    "emotion", "feeling", "sense", "perception", "awareness",
    "consciousness", "mind", "thought", "idea", "memory",
    "imagination", "dream", "fantasy", "vision", "inspiration",
    "motivation", "desire", "ambition", "aspiration", "goal",
    "objective", "aim", "target", "purpose", "intention",
    "plan", "strategy", "tactic", "method", "technique",
    "procedure", "process", "system", "organization", "structure",
    "order", "control", "management", "leadership", "authority",
    "power", "influence", "impact", "effect", "result",
    "outcome", "consequence", "success", "achievement", "victory",
    "triumph", "win", "gain", "profit", "benefit",
    "advantage", "edge", "lead", "progress", "growth",
    "development", "improvement", "advancement", "innovation",
    "breakthrough", "discovery", "invention", "creation",
    "production", "manufacturing", "engineering", "design",
    "construction", "building", "architecture", "structure",
    "form", "shape", "pattern", "style", "design",
    "art", "craft", "skill", "talent", "ability",
    "gift", "genius", "mastery", "expertise", "knowledge",
    "understanding", "wisdom", "insight", "intelligence",
    "perception", "awareness", "consciousness", "mind",
    "thought", "idea", "memory", "imagination", "dream",
    "fantasy", "vision", "inspiration", "motivation",
    "desire", "ambition", "aspiration", "goal", "objective"
]



random_word = random.choice(hangman_words)

