import random

hangman_words = [
    "Mystery", "Adventure", "Giraffe", "Bicycle", "Whisper", "Pyramid", "Galaxy", "Chocolate", 
    "Elephant", "Rainbow", "Castle", "Treasure", "Horizon", "Volcano", "Oxygen", "Universe", 
    "Phoenix", "Tornado", "Dragon", "Astronaut", "Diamond", "Keyboard", "Butterfly", "Crocodile", 
    "Lighthouse", "Icicle", "Snowflake", "Puzzle", "Penguin", "Banana", "Cactus", "Mountain", 
    "Safari", "Jungle", "Robot", "Vampire", "Compass", "Lightning", "Guitar", "Zombie", 
    "Emerald", "Potion", "Unicorn", "Starlight", "Voyage", "Mermaid", "Pirate", "Shark", 
    "Orchestra", "Candle", "Trapeze", "Meteor", "Insect", "Labyrinth", "Telescope", "Spaceship", 
    "Carnival", "Notebook", "Piano", "Clockwork", "Raccoon", "Abyss", "Eclipse", "Cyclone", 
    "Spectacle", "Banquet", "Magician", "Ballet", "Ocean", "Forest", "Vortex", "Submarine", 
    "Specter", "Harmony", "Kingdom", "Zephyr", "Sphinx", "Crescent", "Fossil", "Nebula", 
    "Alchemy", "Bonfire", "Falcon", "Avalanche", "Serpent", "Glimmer", "Parachute", "Chandelier", 
    "Glacier", "Quicksand", "Thunderstorm", "Rendezvous", "Blizzard", "Hologram", "Oracle", 
    "Mariner", "Quagmire", "Galleon", "Fireworks", "Moonlight", "Echo", "Harbor", "Shipwreck", 
    "Galactic", "Enigma", "Cascade", "Harbinger", "Mirage", "Dolphin", "Avalon", "Kingfisher", 
    "Stargazer", "Euphoria", "Wanderlust", "Meadow", "Frostbite", "Cloak", "Timepiece", "Navigator", 
    "Aurora", "Dragonfly", "Shoreline", "Equinox", "Silhouette", "Basilisk", "Moonbeam", "Prism", 
    "Vanguard", "Voyager", "Eldritch", "Evergreen", "Infinity", "Astronomy", "Lantern", 
    "Serenade", "Quicksilver", "Seafarer", "Cryptic", "Solstice", "Serendipity", "Epiphany", 
    "Ethereal", "Turbulence", "Aegis", "Odyssey", "Sapphire", "Equilibrium", "Excalibur", 
    "Radiance", "Celestial", "Avalanche", "Paragon", "Cosmic", "Solitude", "Galactic", 
    "Moonlit", "Oasis", "Zenith", "Quasar", "Frost", "Tranquil", "Nebula", "Storm", 
    "Thunder", "Aether", "Bliss", "Eclipse", "Orion", "Nova", "Constellation", "Supernova", 
    "Polaris", "Celestial", "Meteorite", "Comet", "Interstellar", "Galaxy", "Astronaut", 
    "Astronomy", "Nebula", "Cosmos", "Voyager", "Vortex", "Lunar", "Solar", "Quasar", 
    "Blackhole", "Milkyway", "Orbit", "Planet", "Saturn", "Jupiter", "Mars", "Venus", 
    "Earth", "Moon", "Asteroid", "Comet", "Meteor", "Gravity", "Space", "Lightyear", 
    "Wormhole", "Galaxy", "Star", "Universe", "Sun", "Rocket", "Satellite", "Alien", 
    "Astronomy", "Eclipse", "Meteor", "Blackhole", "Supernova", "Andromeda", "Solar", 
    "Lunar", "Cosmos", "Space", "Orbit", "Galaxy", "Milkyway", "Asteroid", "Planet", 
    "Star", "Gravity", "Comet", "Earth", "Mars", "Jupiter", "Neptune", "Saturn", 
    "Venus", "Pluto", "Uranus", "Mercury", "Orbit", "Rotation", "Eclipse", "Lunar", 
    "Supernova", "Meteorite", "Blackhole", "Galactic", "Stellar", "Nebula", "Quasar", 
    "Asterism", "Redshift", "Bluegiant", "Redgiant", "Whitehole", "Gamma", "Quanta", 
    "Pulsar", "Quasar", "Darkmatter", "Antimatter", "Neutrino", "Photon", "Wavelength", 
    "Horizon", "Event", "Singularity", "Ion", "Atom", "Particle", "Energy", 
    "Frequency", "Amplitude", "Wavelength", "Spectrum", "Infrared", "Ultraviolet", 
    "Quantum", "Theory", "Relativity", "Gravity", "Nucleus", "Electron", "Proton", 
    "Neutron", "Quark", "Higgs", "Boson", "Fermion", "Hadron", "Lepton", 
    "Meson", "Baryon", "Quantum", "Mechanics", "Theory", "Physics", "Science", 
    "Research", "Experiment", "Discovery", "Invention", "Technology", "Engineering", 
    "Mathematics", "Algebra", "Geometry", "Trigonometry", "Calculus", "Statistics", 
    "Probability", "Equation", "Formula", "Algorithm", "Function", "Derivative", 
    "Integral", "Matrix", "Vector", "Tensor", "Transformation", "Symmetry", 
    "Fractal", "Topology", "Number", "Sequence", "Series", "Set", 
    "Group", "Ring", "Field", "Module", "Representation", "Homomorphism", 
    "Isomorphism", "Automorphism", "Endomorphism", "Functor", "Category", 
    "Theory", "Model", "Logic", "Proof", "Theorem", "Lemma", 
    "Corollary", "Axiom", "Postulate", "Conjecture", "Hypothesis", "Law", 
    "Principle", "Concept", "Idea", "Theory", "Hypothesis", "Experiment", 
    "Observation", "Measurement", "Data", "Analysis", "Interpretation", 
    "Conclusion", "Prediction", "Simulation", "Model", "Equation", 
    "System", "Interaction", "Force", "Energy", "Power", 
    "Work", "Momentum", "Impulse", "Acceleration", "Velocity", 
    "Speed", "Distance", "Displacement", "Time", "Clock", 
    "Calendar", "Sun", "Moon", "Star", "Planet", 
    "Satellite", "Spacecraft", "Rocket", "Astronaut", "Mission", 
    "Journey", "Exploration", "Discovery", "Innovation", "Technology", 
    "Research", "Development", "Design", "Engineering", "Invention", 
    "Creativity", "Imagination", "Idea", "Concept", "Project", 
    "Plan", "Strategy", "Tactic", "Method", "Technique", 
    "Procedure", "Process", "Step", "Action", "Movement", 
    "Motion", "Gesture", "Posture", "Pose", "Expression", 
    "Emotion", "Feeling", "Sense", "Perception", "Awareness", 
    "Consciousness", "Mind", "Thought", "Idea", "Memory", 
    "Imagination", "Dream", "Fantasy", "Vision", "Inspiration", 
    "Motivation", "Desire", "Ambition", "Aspiration", "Goal", 
    "Objective", "Aim", "Target", "Purpose", "Intention", 
    "Plan", "Strategy", "Tactic", "Method", "Technique", 
    "Procedure", "Process", "System", "Organization", "Structure", 
    "Order", "Control", "Management", "Leadership", "Authority", 
    "Power", "Influence", "Impact", "Effect", "Result", 
    "Outcome", "Consequence", "Success", "Achievement", "Victory", 
    "Triumph", "Win", "Gain", "Profit", "Benefit", 
    "Advantage", "Edge", "Lead", "Progress", "Growth", 
    "Development", "Improvement", "Advancement", "Innovation", 
    "Breakthrough", "Discovery", "Invention", "Creation", 
    "Production", "Manufacturing", "Engineering", "Design", 
    "Construction", "Building", "Architecture", "Structure", 
    "Form", "Shape", "Pattern", "Style", "Design", 
    "Art", "Craft", "Skill", "Talent", "Ability", 
    "Gift", "Genius", "Mastery", "Expertise", "Knowledge", 
    "Understanding", "Wisdom", "Insight", "Intelligence", 
    "Perception", "Awareness", "Consciousness", "Mind", 
    "Thought", "Idea", "Memory", "Imagination", "Dream", 
    "Fantasy", "Vision", "Inspiration", "Motivation", 
    "Desire", "Ambition", "Aspiration", "Goal", "Objective", 
    "Aim", "Target", "Purpose", "Intention", "Plan", 
    "Strategy", "Tactic", "Method", "Technique", "Procedure", 
    "Process", "System", "Organization", "Structure", "Order", 
    "Control", "Management", "Leadership", "Authority", 
    "Power", "Influence", "Impact", "Effect", "Result", 
    "Outcome", "Consequence", "Success", "Achievement", 
    "Victory", "Triumph", "Win", "Gain", "Profit", 
    "Benefit", "Advantage", "Edge", "Lead", "Progress", 
    "Growth", "Development", "Improvement", "Advancement", 
    "Innovation", "Breakthrough", "Discovery", "Invention", 
    "Creation", "Production", "Manufacturing", "Engineering", 
    "Design", "Construction", "Building", "Architecture", 
    "Structure", "Form", "Shape", "Pattern", "Style", 
    "Design", "Art", "Craft", "Skill", "Talent", 
    "Ability", "Gift", "Genius", "Mastery", "Expertise", 
    "Knowledge", "Understanding", "Wisdom", "Insight", 
    "Intelligence", "Perception", "Awareness", "Consciousness", 
    "Mind", "Thought", "Idea", "Memory", "Imagination", 
    "Dream", "Fantasy", "Vision", "Inspiration", "Motivation", 
    "Desire", "Ambition", "Aspiration", "Goal", "Objective"]


